# ******************************
#           base.yml
#
# Put your alacritty config here 
# ******************************

# The theme config will appear below this comment, it will supersede your changes if you already set them above
